### ISSUE TITLE
GoogleTagManager not working after initial load

### ISSUE THREAD

**Issue by aian23** [xamarin/GooglePlayServicesComponents#358]
Xamarin.Android Version (eg: 6.0):
10.1.4.0

Operating System & Version (eg: Mac OSX 10.11):
Windows 10
I'm using VIsual studio 2019

Describe your Issue
Followed every step right:

FB, GA and TM properly set up
Install necessary nugets as stated below.
Put the JSON of the tag manager container inside assets/containers
When I tested in iOS, it went smoothly.
In Android, everything works on intial load. However if you close the app and launch it again, tag manager doesn't work anymore and the tags are not affecting events logged in FB and GA.

See screenshot for reference.

Relevant information
Add relevant project settings from *.csproj file:

Packages used:

    <PackageReference Include="Xamarin.GooglePlayServices.Analytics" Version="71.1608.1" />
    <PackageReference Include="Xamarin.GooglePlayServices.Base" Version="71.1610.1 />
 <PackageReference Include="Xamarin.GooglePlayServices.TagManager" Version="71.1604.1 />
 <PackageReference Include="Xamarin.Firebase.Analytics" Version="71.1630.1 />
 <PackageReference Include="Xamarin.Firebase.Messaging" Version="71.1740.1 />
Minimal Repro Code Sample
Create a Xamarin Forms app.
In the Android project, install the necessary nuget packages.
Enable firebase and call _firebaseAnalytics.SetAnalyticsCollectionEnabled(true);.
Log some events
Create a GA and google tag manager account. Create a container (Android), then download the JSON file. Put the JSON file inside Assets/containers folder.
Run the application while Device logcat is running (you can check error here)

**Comment by moljac** [comment]
I need more info:

- what is "inital load"?
- what does "FB, GA and TM properly set up" mean? FB is firebase, GA (Google Ads, Google Analytics)? TM (TagManager)?

**Comment by aian23** [comment]
@moljac  - initial load means when you initially install the application and launch it, GTM works as expected and the tags that I set up do what they suppose to. However, if you close the app and launch it again, the tags no longer log the expected events.

That's right, FB is firebase and GTM is google tag manager. GA is google analytics. FB and GA is always working fine as whenever I log something in FB(data layer), it gets logged in GA. It's only the GTM that has the problem.

For proper setup, I just installed these packages:

<PackageReference Include="Xamarin.GooglePlayServices.Analytics" Version="60.x" />
<PackageReference Include="Xamarin.GooglePlayServices.Base" Version="60.x />
<PackageReference Include="Xamarin.GooglePlayServices.TagManager" Version="60.x />
<PackageReference Include="Xamarin.Firebase.Analytics" Version="60.x />
<PackageReference Include="Xamarin.Firebase.Messaging" Version="60.x/>

**Comment by aian23** [comment]
@moljac , to add, I'm seeing this error in the device logcat:

container not loaded yet: deferring event interceptor

**Comment by moljac** [comment]
@aian23 
Those are very old versions. Why are you using those? Can't you try newer versions? 71.x at least, though that is old too.

**Comment by aian23** [comment]
@moljac , I wanted to use the 71.x versions, but unfortunately I'm encountering this error in this issue which hasn't been fixed yet:

https://github.com/xamarin/GooglePlayServicesComponents/issues/260

Any recommendations that might help? Have you recreated the issue?

**Comment by moljac** [comment]
@aian23 
I tried several fixes few months ago, but they did not work. Then I had to switch to other tasks (AndroidX and GPS-FB with AndroidX dependencies 1xx version). I hope that I will find some time for more attempts soon.

> Any recommendations that might help? 

Manifest merger was one from top of my head, but users said that it solved other issues, but not this one.

> Have you recreated the issue?

I have one repro sample from one of the issues you mentioned. I wish I could find some time to go through google tutorials and recreate those samples. That would help me and you.

**Comment by aian23** [comment]
@moljac -  If it helps, I think what's happening is that there's a problem in loading the containers. As I was checking the issue, I saw these in the device log cat when the tag manager event triggers WORK:

![image](https://user-images.githubusercontent.com/10769624/84912638-366b6600-b0ec-11ea-9ab3-10bd329a410d.png)

![image](https://user-images.githubusercontent.com/10769624/84912591-294e7700-b0ec-11ea-9886-909b618bf250.png)

as seen in the screenshots above, what happened was that the container was loaded from the network. I also saw an item that says: "Trigger is firing: Positive predicates...."

However, for the logs that I saw for the times that the event wasnt firing, I saw that the container is only being fetched from a saved resource in the disk. Moreover, I don't see the "Trigger is firing" log. See screenshot below:

![image](https://user-images.githubusercontent.com/10769624/84913051-aa0d7300-b0ec-11ea-9ec2-2403a21eabe4.png)

**Comment by aian23** [comment]
@moljac , just wanted to ask if you ever get a chance to look at these logs or recreate the issue. Thanks!

**Comment by moljac** [comment]
@aian23 yes. I'm currently trying to find workaround for that issue (and few other similar issues).

**Comment by aian23** [comment]
@moljac awesome. Excited with this update! What was the cause of this issue? Hoping you would be able to find a workaround for this. Thanks!!

**Comment by moljac** [comment]
@aian23 

> What was the cause of this issue?

Not sure yet. Either bug in tooling or limitations in tooling (differences between java and c# idioms which are difficult to map 1:1)

> Hoping you would be able to find a workaround for this.

If I cannot there are guys who will able to help. For sure.

**Comment by aian23** [comment]
@moljac I see, so it's actually mapping. I'll just be monitoring this one here and hope it gets fixed soon.. I'm sure a lot of devs will be happy also. :)

**Comment by aian23** [comment]
@moljac  - Good day! Just wanted to ask if you were able to find some fixes or workaround for this. THanks!

**Comment by aian23** [comment]
@moljac , ano updates on this issue? A lot of our work has been affected by this issue so we are very keen to check if there are any potential fixes or updates for this. Thanks!

**Comment by aian23** [comment]
@moljac , any updates on this issue? A lot of our work has been affected by this issue so we are very keen to check if there are any potential fixes or updates for this. Thanks!

**Comment by moljac** [comment]
@aian23 
I need to fix few smaller AndroidX issues and some of those affect GPS-FB. I hope this week.

**Comment by aian23** [comment]
@moljac thanks for the update. Looking forward for the fix for this issue this week. We're really keen on getting it. Cheers!

**Comment by moljac** [comment]
@aian23 Doing my best, but keep on hitting obstacles. I had to update cake scripts and request update from few tool authors, because CI builds were failing due to older dependencies and new dotnet core installed. Good news is that it is solved (IMO)

**Comment by aian23** [comment]
@moljac really appreciate the updates and I'm real glad that it is now fixed. Hope you get over the CI hump so those builds get through. Really appreciate it!

**Comment by moljac** [comment]
OK. Seems I managed to cleanup + update + upgrade everything for CI, so now local builds and CI are green.

I am starting to tag branches. i wil not release stable versions yet, but most likely next week.

**Comment by aian23** [comment]
Thanks for the update @moljac ! So is there an available pre-release version already? Keen to test it while I await the stable versions but this is absolutely great news!

**Comment by moljac** [comment]
Published all 4 branches.

I hope that `remove-node` will work. That was brute force solution/workaround in the past. Otherwise I need to dig in deeper and see what is going on. One of the biggest problems is that google is shifting namespaces and code from artifact to artifact.

**Comment by moljac** [comment]
OK. Wrong tag for 71.
Retagging

**Comment by aian23** [comment]
@moljac  thanks for the update! Just wanted to clarify, so have you already published a minor version for v60? When I checked the nuget, I wasn't able to see a new minor version for v60:

![image](https://user-images.githubusercontent.com/10769624/87644168-5be89f80-c77e-11ea-84b9-0dfd2cbbe549.png)

Is this the case?

**Comment by moljac** [comment]
@aian23 Trying to fix 71.xyz, but problems on CI and outdated sample projects.
Can you try those published and provide feedback, so I can see if i did hit the sweet spot. Namely I removed node (the whole internal namespace/package). This usually works, but I hate to say it is solved. And I simply have no time to work on samples.

60.xyz will not be fixed for sure.
71.xyz only because I said so (I'm the man - decision man in this case, cos I'm the only one)

**Comment by aian23** [comment]
@moljac no worries, I understand if it gets fixed in 71.xyz. I checked the nuget package versions just earlier but I can't see a new version for 71.xyz:

![image](https://user-images.githubusercontent.com/10769624/87674393-851e2580-c7a8-11ea-8911-2bf90228095b.png)

The latest version for 71.xyz that I'm seeing was updated last 5/12/2020 so I'm a but confused. Can you guide me with the steps so I can try the changes you made?

**Comment by moljac** [comment]
@aian23 I have problems with lane (build for 71.xyz - curently on master). Could you try other newer packages please, 1xx (I pushed 2 version then i wanted to do 71 and got stuck on CI)

**Comment by aian23** [comment]
@moljac I see.. I thought the CI issues were already resolved. I tried using the 1xxx versions in the past but our app doesn't have support for Android X yet and so it's not compatible. Perhaps in the future we can upgrade to it (Im assuming it also has the fix right?) but not right now. I hope the builds for 71.xyz can push through so I can test those ones since those are compatible with our app. Hope you understand and hoping for luck in the builds

**Comment by moljac** [comment]
@aian23 
I fixed 3 100.xyz branches (bindings and tooling versions) with GPS-FB with AndroidX dependencies, but not 71.x. That branch (curently master soon 71-android-support) was "neglected" and it is quite different from 100.xyz with respect of tooling.

All 4 (3+1) branches have the same fix and I just published 71 nugets with TagManager and several other fixes.

Please try them out and provide me/us feedback if the problem was solved.

**Comment by aian23** [comment]
@moljac - thanks for the update. I'll get back to you as soon as I am able to test. It's already late here already so I'll probably be able to check this on 7/20 (Monday). Thanks!

**Comment by aian23** [comment]
@moljac  thanks for the feedback. I tried testing it right now using the new 71.1630.4. I used the ff nuget:

Xamarin.Firebase.Analytics       <Version>71.1630.4</Version>
Xamarin.Firebase.Core      <Version>71.1601.4</Version>
Xamarin.Firebase.Messaging      <Version>71.1740.4</Version>
Xamarin.GooglePlayServices.Base      <Version>71.1610.4</Version>
Xamarin.GoogePlayService.TagManager      <Version>71.1604.0</Version>

After doing so, the google tag manager still isn't working. Moreover, I noticed that this time, the containers aren't even being loaded. In the previous versions, the containers are still being loaded. Here's some info that I got from device log cat:

![image](https://user-images.githubusercontent.com/10769624/87786238-2fab4c80-c86c-11ea-8cdd-df7a59961455.png)

**Comment by aian23** [comment]
@moljac  were you able to check last Friday why the changes didn't fix the issue? Thanks!

**Comment by aian23** [comment]
@moljac were you able to check last Friday why the changes didn't fix the issue? Let me know if I can help out by providing more logs and information.

**Comment by moljac** [comment]
@aian23 

See https://github.com/xamarin/GooglePlayServicesComponents/issues/260#issuecomment-661898867

**Comment by aian23** [comment]
@moljac - tried this our earlier, but GTM still isn't working. Here are the logs that I saw:

![image](https://user-images.githubusercontent.com/10769624/88173647-81c9e480-cc55-11ea-8538-368898ae84ee.png)
![image](https://user-images.githubusercontent.com/10769624/88173659-85f60200-cc55-11ea-8c97-8e6cee1165b7.png)

**Comment by aian23** [comment]
@moljac - was wondering if you want to reconsider checking the v60 versions since the GTM is working in Android in this version, although it only works erratically. At least it's already working and we may just need to check why it works erratically. Maybe you can also find clues in that version and why it works somewhat in that and not in the higher versions? We really need a fix for this as GTM works erratically in Android while using v60. The v71 versions on the other hand don't work at all.

Hoping to hear your thoughts

**Comment by aian23** [comment]
@moljac - Good day! Would just like to ask if you have any ideas with the cause of the issue or if you want to consider the suggestion above. We just really need the fix right now as this is very urgent. Hoping you could take a look into this once again.

**Comment by moljac** [comment]
@aian23 

>  if you want to reconsider checking the v60 versions since the GTM is working in Android in this version, 

I'm sorry, but I will not have time for that. I wish I could help you. I will not test v.60 for sure. v 71.x.y maybe. 

Ping me at mcvjetko `{at}` holisticware.net by mail.

**Comment by aian23** [comment]
@moljac  I see. Do you have any lead as to why the V71.xyz still isn't working for GTM?

**Comment by GreenRock** [comment]
Hi @moljac 
I think we missed the package com.google.firebase.measurement_impl. Could you spend a little time to check it?
I saw the error when init Tag Manager 
`Warning (27963) / FA: Failed to invoke Tag Manager's initialize() method: java.lang.reflect.InvocationTargetException: com.google.android.gms.measurement.internal.zzda.zza(Unknown Source:97)
`
I found 'com.google.android.gms.measurement.internal.zzda.zza' it's in com.google.firebase.measurement_impl
![image](https://user-images.githubusercontent.com/4007699/94785925-8996c980-03fa-11eb-854f-dabc21ea85e9.png)
Thanks for your time

**Comment by GreenRock** [comment]
Hi @moljac 
I think we missed the package com.google.firebase.measurement_impl. Could you spend a little time to check it?
I saw the error when init Tag Manager 
`Warning (27963) / FA: Failed to invoke Tag Manager's initialize() method: java.lang.reflect.InvocationTargetException: com.google.android.gms.measurement.internal.zzda.zza(Unknown Source:97)
`
I found 'com.google.android.gms.measurement.internal.zzda.zza' it's in com.google.firebase.measurement_impl
![image](https://user-images.githubusercontent.com/4007699/94786919-ca431280-03fb-11eb-96dc-f8fede151666.png)
Thanks for your time

**Comment by moljac** [comment]
@GreenRock Thanks for the feedback

> I think we missed the package com.google.firebase.measurement_impl. Could you spend a little time to check it?

Sure. But what does "missed the package" mean?

I'm slightly confused: in the text you mention `com.google.firebase.measurement_impl`, but in the image there is `play-services-measurement-impl-17.0.0.aar`

Yes google shuffles classes and libraries all around and it is not trivial to keep track of that. THanks for pointing out

**Comment by GreenRock** [comment]
Hi @moljac 
Thanks for your time. 
Yes, it's play-services-measurement-impl-17.0.0.aar, package name in AndroidManifest is com.google.firebase.measurement_impl
![image](https://user-images.githubusercontent.com/4007699/95035764-42595300-06f0-11eb-851f-3f4e2b6d5b42.png)

**Comment by GreenRock** [comment]
Hi @moljac 
GTM is working with 
`
<PackageReference Include="Xamarin.Firebase.Analytics">
      <Version>117.4.1-preview02</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.TagManager">
      <Version>117.0.0-preview04</Version>
    </PackageReference>
`
But it does not work on 71.x.

**Comment by katariyaprakash7** [comment]
Hi @GreenRock Can you please guide me on how we can integrate the GTM SDK for xamrin native android app.

I have firebase integrated successfully and now try to add the GTM SDK here. but not able to load the GTM container.

Can you guide me with the steps to integrate the GTM SDK here?
http://prntscr.com/1jyiz9c

Thanks in advance!!

**Comment by GoldenGlitterBug** [comment]
@Moljac @GreenRock I have upgraded following packages: 

```
   <PackageReference Include="Xamarin.Firebase.Analytics">
      <Version>117.4.1</Version>
   </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.TagManager">
       <Version>117.0.0</Version>
    </PackageReference>
```
and removed:    
```
    <PackageReference Include="Xamarin.Firebase.Analytics.Impl">
       <Version>71.1630.4</Version>
    </PackageReference>
```
I am testing it on emulator. Seeing the same error in Android Adb command prompt:
```
Failed to invoke Tag Manager's initialize() method: java.lang.reflect.InvocationTargetException: com.google.android.gms.measurement.internal.zzda.zza(Unknown Source:97)
```
Also I tried updating packages to latest version. Nothing works.
```
   <PackageReference Include="Xamarin.Firebase.Analytics">
      <Version>119.0.1</Version>
   </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.TagManager">
       <Version>117.0.1</Version>
    </PackageReference>
```

**Comment by GreenRock** [comment]
Hi @GoldenGlitterBug 

I did not work with Xamarin for 3 months ago. Not sure it'll work. However, You can try it for yourself. 

`<PackageReference Include="Xamarin.Google.Android.DataTransport.TransportBackendCct">
      <Version>2.3.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Google.Android.DataTransport.TransportRuntime">
      <Version>2.2.5</Version>
    </PackageReference>
     <PackageReference Include="Xamarin.AndroidX.Migration" Version="1.0.8" />
   <PackageReference Include="Xamarin.Firebase.Messaging">
      <Version>121.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.Dynamic.Links">
      <Version>119.1.1</Version>
    </PackageReference>
      <PackageReference Include="Xamarin.Google.Dagger">
      <Version>2.27.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.Base">
      <Version>117.6.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.Analytics">
      <Version>118.0.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.TagManager">
      <Version>117.0.0</Version>
    </PackageReference>
     <PackageReference Include="Xamarin.Firebase.Crashlytics">
      <Version>117.3.1</Version>
    </PackageReference>`

    Make sure you have this package. 
    `      
    <PackageReference Include="Xamarin.Google.Dagger">
      <Version>2.27.0</Version>
    </PackageReference>
    `

**Comment by GoldenGlitterBug** [comment]
@GreenRock It's working. I was able to connect to GTM and execute test Tags.

@moljac @GreenRock  Thanks very much!!
