### ISSUE TITLE
Firebase Token not Registered

### ISSUE THREAD

**Issue by alberk8** [xamarin/GooglePlayServicesComponents#57]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android = 7.2.0.7

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 Professional - Visual Studio 2015

### Google Play Services Version (eg: 8.4.0):
Xamarin.Firebase.Messaging 10.2.1 V42.1021.0-beta-1

### Describe your Issue:
The code below will work when I build and install the release version for the very first time on a physical mobile phone Android Lollipop.  Subsequent build/rebuild to the release version the token value returned will be exactly the same as the first instance but sending message from the Firebase website will return an error saying "unregistered registration token".  

firebaseinstanceid = FirebaseInstanceId.Instance;
Log.Info(TAG, "Service Firebase Token: " + firebaseinstanceid.Token.ToString());

### Steps to Reproduce (with link to sample solution if possible):
1) Build the app as release version and install from VS.  Send message from Firebase website.
First time no problem the token is good. (make sure the app is not install in the mobile phone).

2) Rebuild App as release version and install from VS, Token value returned by the Firebase method still the same as first install but now the firebase website shows. "Unregistered Registration Token"

### Include any relevant Exception Stack traces, build logs, adb logs:
-- No error from adb logs or onMessage

My question is why is the Firebase Server knows that the token is invalid but the Firebase method in my app is not refreshing the token?

> VS bug [#732435](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732435)

**Comment by guiwaltricke** [comment]
@alberk8 the same problem here... the Stackoverflow has many others with the same problem... anyone knows a workaround?

**Comment by iTruff** [comment]
Same problem. Last few days sometimes i cannot even obtain firebase token...

**Comment by bovisfeldt** [comment]
same problem here. Gonna keep using GCM until solved.

**Comment by snboisen** [comment]
Seriously Xamarin, this issue is from April, it is bad (blocks use of Firebase) and no-one from the team has responded in any way in all this time. Has all Xamarin development been stopped? Or just the really important parts such as addressing critical bugs?

**Comment by jcarlos79t** [comment]
Señores de Xamarin- Microsoft por favor solución.

**Comment by tanwarsatya** [comment]
the issue is still very much active , any solution for this or we have to use GCM ?

**Comment by ahumeniy** [comment]
It's October, this is still an issue

**Comment by enenter** [comment]
November... I still have to uninstall and rebuild the app before each launch when testing firebase.

**Comment by emgapps** [comment]
Almost December. Same situation.

**Comment by Redth** [comment]
While I'm trying to reproduce this, has anyone tried without fast-deploy enabled?

**Comment by Redth** [comment]
So far I've had zero success in reproducing this issue.

VS 2017 on Windows, latest Xamarin and Visual Studio updates as of 2017-12-05

I'm using Firebase Messaging 60.1142.0-rc1 and compiling against Android 8.0 (API 26).

I setup my test.keystore's sha1 signature in the Firebase Console for my app, downloaded the google-services.json file and added it to my project with a GoogleServicesJson build action type.

My app is set to use the same keystore for each release build via the .csproj:

```
<PropertyGroup>
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningKeyStore>test.keystore</AndroidSigningKeyStore>
    <AndroidSigningStorePass>test</AndroidSigningStorePass>
    <AndroidSigningKeyAlias>test</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>test</AndroidSigningKeyPass>
  </PropertyGroup>
```

I tried building and deploying to device, the app runs, I get a token, and I can use the Firebase Console to send a test message to it.

Next, I changed a bit of code, cleaned my project, and built it again.  I deployed to the device and again got the same token as the previous build.  I sent another message through the Firebase Console and received it successfully.

If anyone's got more insight into what I'm missing in trying to reproduce this, please let me know.

**Comment by ahumeniy** [comment]
It may be because you're using the RC version of Firebase Messaging.

De: Jonathan Dick<mailto:notifications@github.com>
Enviado: martes, 5 de diciembre de 2017 17:21
Para: xamarin/GooglePlayServicesComponents<mailto:GooglePlayServicesComponents@noreply.github.com>
CC: Alexei Humeniy<mailto:yo@ahumeniy.net>; Comment<mailto:comment@noreply.github.com>
Asunto: Re: [xamarin/GooglePlayServicesComponents] Firebase Token not Registered (#57)


So far I've had zero success in reproducing this issue.

VS 2017 on Windows, latest Xamarin and Visual Studio updates as of 2017-12-05

I'm using Firebase Messaging 60.1142.0-rc1 and compiling against Android 8.0 (API 26).

I setup my test.keystore's sha1 signature in the Firebase Console for my app, downloaded the google-services.json file and added it to my project with a GoogleServicesJson build action type.

My app is set to use the same keystore for each release build via the .csproj:

<PropertyGroup>

    <AndroidKeyStore>True</AndroidKeyStore>

    <AndroidSigningKeyStore>test.keystore</AndroidSigningKeyStore>

    <AndroidSigningStorePass>test</AndroidSigningStorePass>

    <AndroidSigningKeyAlias>test</AndroidSigningKeyAlias>

    <AndroidSigningKeyPass>test</AndroidSigningKeyPass>

  </PropertyGroup>

I tried building and deploying to device, the app runs, I get a token, and I can use the Firebase Console to send a test message to it.

Next, I changed a bit of code, cleaned my project, and built it again. I deployed to the device and again got the same token as the previous build. I sent another message through the Firebase Console and received it successfully.

If anyone's got more insight into what I'm missing in trying to reproduce this, please let me know.

**Comment by Redth** [comment]
That's possible.  However we just provide bindings to googles' libraries, so if it's working on this version as opposed to older versions i'm inclined to say Google has fixed a bug on their end.

60.1142.0-rc1 will be going stable today or tomorrow.  I'd suggest you try with that version.

**Comment by craylward** [comment]
Still an issue for me
VS for Mac 2017
Xamarin.Android 8.2.0.16
Xamarin.Firebase.Messaging 60.11.42.1
Xamarin.GooglePlayServices.Base 60.1142.1

Device registers and receives FCM token successfully shown by log output. Sending first message on Firebase console shows as "Completed" but message it not received by app. Subsequent messages fail with error "Unregistered registration token".

**Comment by NGumby** [comment]
I had this problem, took me way to many hours to figure it out, but in my AndroidManifest.xml, the receiver tags where not inside the application tag.

before
```
<application android:label="MyApp" android:icon="@drawable/icon"></application>
<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
  <intent-filter>
    <action android:name="com.google.android.c2dm.intent.RECEIVE" />
    <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
    <category android:name="${applicationId}" />
  </intent-filter>
</receiver>
```
after
```
<application android:label="MyApp" android:icon="@drawable/icon">
    <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
    <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
        <category android:name="${applicationId}" />
      </intent-filter>
    </receiver>
  </application>
```

**Comment by PureWeen** [comment]
Here are some recreation samples. Initially I was seeing this issue when tied to Azure Push Notification


[FirebaseIssueAzurePush.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/1917456/FirebaseIssueAzurePush.zip) 
I have all the components libraries updated to the latest version.  I've tested this on VSfM and VSfW

basically
- setup the google-services.json file with your configuration.  
- debug deploy the app to an android device
- now if you use the firebase console or the azure notification hub to send a message it will work
- stop app and debug deploy app again
- now if you try to use firebase console to send a message it'll say "token unregistered"

When I have the Azure Mobile packages installed, whenever I f5 it does a build of the Android project. Even if I haven't changed any files it still does a build of the Android project and causes the issue

So I created a second sample

[FirebaseIssueSimple.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/1917455/FirebaseIssueSimple.zip)

This sample has Azure Mobile bits totally removed. With this sample if I f5 without making any changes then the token stays valid between f5's. But if you change anything on the android project (like add a space somewhere) then f5 the token becomes invalidated and doesn't refresh.

Ideally in either case if that token becomes invalidated it'd be nice for it to refresh.
In both cases the static Token field still holds the old invalid token

```C#
  if (!string.IsNullOrWhiteSpace(Firebase.Iid.FirebaseInstanceId.Instance.Token))
                    {
                        Console.WriteLine(Firebase.Iid.FirebaseInstanceId.Instance.Token);
                    }
```

**Comment by PureWeen** [comment]
@Redth   I tested using this sample
https://github.com/firebase/quickstart-android/tree/master/messaging

And AFAICT the token never gets invalidated
- released app to device
- messaging worked
- made a code change then released app to device
- messaging worked
- build => clean project
- released app to device
- messaging worked

At no point did it try to re-issue me a token. The same token just kept on working through the process

**Comment by Redth** [comment]
Seems like we _must_ do something different in our deploy to cause this.

**Comment by zlatko5** [comment]
Has this issue been further investigated since 18-Apr? Any progress?

**Comment by thefex** [comment]
check if AndroidManifest.xml is same both in not working (release?) and working (debug?) version. (analyze both APKs through Android studio Analyze APK feature)
I had an issue with other library - somehow release version got some autogenerated <receivers>/<services> (through [Service]/[BroadcastReceiver] etc attributes) removed on Release version. The solution was to add services/broadcast receivers manually (copy paste from working APK AndroidManifest binary) in AndroidManifest.xml

**Comment by Redth** [comment]
Thanks for that suggestion.

**Comment by kyluke** [comment]
Any update on this? It's still a problem.

**Comment by moljac** [comment]
Closing this one.
Try newer libraries.
For older versions add Xamarin.Android.ManifestMerger.
if the issue persists - open new one, please.
